version: "3"

services:

  jupyter:
    build: ./app
    volumes:
      - ./app:/app
    networks:
      - neo4j_network
    container_name: python-andrei
    depends_on:
      - neo4j

  neo4j:
    container_name: neo4j-andrei
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    networks:
      - neo4j_network

networks:
  neo4j_network:
    driver: bridge